spring.application.name=demo
# ????????? ??????????? ? ??
spring.datasource.url=jdbc:postgresql://localhost:5433/game_server_db
spring.datasource.username=postgres
spring.datasource.password=05.03.Vova

# ????????? Hibernate (ORM)
# update ????????, ??? Hibernate ??? ??????? ???????, ???? ?? ???,
# ? ??????? ????? ??? ????????? ????
spring.jpa.hibernate.ddl-auto=update

# ???????? ??????????? SQL-???????? ? ???????
# ??? ????? ??????? ??? ???????, ????? ??????, ????? ?????? ??????? ?????? ? ????
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

telegram.bot.name=lisha_find_bot
telegram.bot.token=8620666044:AAHicv5kJbTvkEaA0ZSZxv1EETf3kxbFQhs